<a href="https://colab.research.google.com/github/valleryuh/CSST-101/blob/main/BSCS3B_DE_GUZMAN_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

My First  R Program

1. Print

In [ ]:
print ("Hello World")

[1] "Hello World"

2. String Variable

In [ ]:
myString <- ("Hello World")
print(myString)

[1] "Hello World"

Multi Char

In [ ]:
myString <- ("Hello World")
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingNum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3.Numerical Operators

In [ ]:
x <- 5
y <-3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y
exp <- x ^ y

print(add)
print(sub)
print(mul)
print(div)
print(exp)

cat("+", add)
cat("-", sub)
cat("*", mul)
cat("/", div)
cat("^", exp)

[1] 8
[1] 2
[1] 15
[1] 1.666667
[1] 125
+ 8- 2* 15/ 1.666667^ 125

4. User Input

In [ ]:
name <- readline("Enter Name ")
print(paste("Name:", name))

Enter Name Rhea
[1] "Name: Rhea"

5. Decision Making

In [ ]:
grade <- 80

if(grade <75)(
print("Failed")
)else(
print ("Passed")
)

[1] "Passed"

[1] "Passed"

6. Loop

In [ ]:
for(i in 1:5){
print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Function

In [ ]:
addNumber <- function (a,b){
return (a+b)
}

addNumber(5,3)

[1] 8

8. Vectors

In [ ]:
grades <- c(90, 88, 96, 83, 91)

grades

cat("MEAN: ", mean(grades))
cat("\nMax: ", max(grades))
cat("\nMin: ", sum(grades))
cat("\nLength: ", length(grades))

[1] 90 88 96 83 91

MEAN:  89.6
Max:  96
Min:  448
Length:  5

9. Matrices

In [ ]:
A <- matrix(c(1,2,3,4,5,6,7),nrow=2)
A

Warning message in matrix(c(1, 2, 3, 4, 5, 6, 7), nrow = 2):
“data length [7] is not a sub-multiple or multiple of the number of rows [2]”

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    1

10. List

In [ ]:
student <- list(
Name="nie",
Age=20,
GPA= 1.5
)
student

$Name
[1] "nie"

$Age
[1] 20

$GPA
[1] 1.5

11. Data Frame

In [ ]:
students <- data.frame(
Name=c("Jhoena","Rafa","Melrose"),
Age=c(20,21,20),
GPA=c(1.74, 1.25, 1)
)

students

write.csv(students,"student.csv")

  Name    Age GPA
1 Jhoena  20  1.74
2 Rafa    21  1.25
3 Melrose 20  1.00

12. Read csv File

In [ ]:
data <- read.csv("student.csv")

head(data)
summary(data)

  X Name    Age GPA
1 1 Jhoena  20  1.74
2 2 Rafa    21  1.25
3 3 Melrose 20  1.00

       X              Name        Age             GPA
 Min.   :1.0   Length   :3   Min.   :20.00   Min.   :1.000
 1st Qu.:1.5   N.unique :3   1st Qu.:20.00   1st Qu.:1.125
 Median :2.0   N.blank  :0   Median :20.00   Median :1.250
 Mean   :2.0   Min.nchar:4   Mean   :20.33   Mean   :1.330
 3rd Qu.:2.5   Max.nchar:7   3rd Qu.:20.50   3rd Qu.:1.495
 Max.   :3.0                 Max.   :21.00   Max.   :1.740